<!DOCTYPE html>
<html>
<head>
    <link href="styles.css" rel="stylesheet"/>
</head>
<body>
<div>
    <h1>
        <?php
        $number = 10;
        $collection = array('Me', 'You', 'Friends');

        echo 'My first PHP script!' . '</br>';
        echo 'Value of the number is: ' . $number . '</br>';

        for ($i = 1; $i <= $number; $i++) {
            if ($i % 2 != 0) {
                echo 'odd ' . $i . '</br>';
            } else {
                echo 'even ' . $i . '</br>';
            }

        }

        foreach ($collection as $item) {
            echo $item . '  ';
        }

        ?>
    </h1>
</div>
</body>
</html>